### ISSUE TITLE
Kirby Panel Textarea wysiwyg

### ISSUE THREAD

**Issue by jenstornell** [jenstornell/kirby-plugins#111]
https://github.com/julien-gargot/kirby-wysiwyg

> A simple integration of the markdown wysiwyg from on Hallo.js developed by Henri Bergius.

**Comment by samnabi** [comment]
The URL gives a 404 now.

**Comment by aoimedia** [comment]
Thanks for the update. Looks like the project is now private or deleted. Now closed.

**Comment by julien-gargot** [comment]
Hi everyone, 
I didn’t see this repo what mentioned here.
I delete it, it was irrelevant in front of the great http://www.getkirby-plugins.com/visual-markdown-editor. ;)
