### ISSUE TITLE
Splitview

### ISSUE THREAD

**Issue by jenstornell** [jenstornell/kirby-plugins#114]
**Github:** https://github.com/jenstornell/splitview

![Alt text](https://raw.githubusercontent.com/jenstornell/splitview/master/assets/images/dist/screenshot-1.png)

> Splitview makes it possible to edit your pages in a splitscreen view. See what you change directly after pressing save.

**Comment by jenstornell** [comment]
Closed because it was not good enough.

**Comment by medienbaecker** [comment]
What do you mean by "not good enough"? I thought it was a really clever solution.

**Comment by aoimedia** [comment]
@medienbaecker the man is a perfectionist! ;)

**Comment by jenstornell** [comment]
@medienbaecker 

The main thing was that I figured out that it was better to build this kind of tool from inside the panel. The replacement for it is https://github.com/jenstornell/kirby-reveal.

I'm not completely happy with some details in the reveal plugin so I've not made a big announcement about it yet.

@aoimedia 

LOL, you think? :D

**Comment by jenstornell** [comment]
@medienbaecker If you are interested in continuing with the development of Splitview, just let me know and I'll give you the repo. Else I will delete it 1 feb.

**Comment by medienbaecker** [comment]
@jenstornell I'm afraid my development skills are not on par with yours. So I could easily turn "not good enough" into "not working at all" really quick, but nothing else. Sorry.
