### ISSUE TITLE
Place Field

### ISSUE THREAD

**Issue by jenstornell** [jenstornell/kirby-plugins#127]
**GitHub** https://github.com/AugustMiller/kirby-place-field

> - Familiar Google Maps UI
> - Discrete storage of location name, latitude and longitude
> - Geocoding of place names and addresses
> - Repositionable marker (in case search doesn't nail it)
> - Support for multiple place fields per form
> - Support for place fields within structure fields.
> - Easy to implement (See "Getting Started", below)
> - Customizable default position and zoom— globally and on a per-field basis

![](https://raw.githubusercontent.com/AugustMiller/kirby-place-field/master/screenshot.png)

**Comment by aoimedia** [comment]
Deprecated.
