### ISSUE TITLE
Kirbydrop Plugin

### ISSUE THREAD

**Issue by aoimedia** [jenstornell/kirby-plugins#128]
https://github.com/cemk/kirbydrop

Kirbydrop is a Kirby CMS theme to list your Dropshare uploads.

**Comment by jenstornell** [comment]
I have not yet figured out what to do with themes. Keep them here, or create a separate repository for it. What do you think?

**Comment by aoimedia** [comment]
That's a good point. Perhaps a separate repo is best for themes. Or perhaps a name change… 

“kirby-extras” ? ;)

**Comment by jenstornell** [comment]
Yes, something like that. I would like to have snippets, templates, blueprint and solutions somewhere as well. The things that are not complete plugins but a great help when developing.

**Comment by aoimedia** [comment]
Agreed. Seems a shame to miss out on themes, snippets, temps and blueprints. These are as important to some users as plugins are when it comes to development (and can be great learning tools).
