### ISSUE TITLE
Feed plugin

### ISSUE THREAD

**Issue by jenstornell** [jenstornell/kirby-plugins#13]
https://github.com/studiodumbar/kirby-extensions/tree/master/plugins/feed

> A RSS feed plugin for Kirby CMS that generates RSS feeds for any set of pages.

**Comment by Thiousi** [comment]
Plugin doesn't exist at the given URL anymore.

**Comment by aoimedia** [comment]
Thanks. Closing this as it looks like plugin no longer exists.
