### ISSUE TITLE
kirbylog

### ISSUE THREAD

**Issue by aoimedia** [jenstornell/kirby-plugins#145]
https://github.com/kimfranken/kirbylog

Lightweight blog theme for Kirby CMS.

**Comment by jenstornell** [comment]
I started the repo https://github.com/jenstornell/kirby-themes so if you have found a theme you can start posting them as issues there.

I also added you as collaborator. I don't know exactly what you get by that. Hopefully you can add labels but I'm not sure of that.

**Comment by aoimedia** [comment]
Hi Jens,

Thanks. Just had a look and it appears that I can add labels etc.

I'll now post themes to the new 'themes repo'. 

What about themes that are currently posted to the 'kirby-plugins' repo? Will you move these over to the new 'themes' repo, or do you want me to do that?

Also, I know of a few free Kirby themes that are _not_ hosted on GitHub. Do you want me to add these purely as reference (with a link to the original source) or are you looking to concentrate on GitHub repos only?

**Comment by jenstornell** [comment]
If you move them you will save me time. Else I will move them later on.

I have 1 plugin that does not exist on Github in the list (of 164). I don't think Github should be required, but if the theme/plugin exists on both a website and on Github I would prefer the Github link, but it depends. Maybe there are no docs at all on Github. In that case maybe add both urls.

**Comment by aoimedia** [comment]
No problem, I'm happy to move them.

However, I don't see any way of pulling/pushing 'issues' from separate repos. In this respect I may need to just duplicate them on the new repo. You could remove them from the plugins repo when I've completed this.

**Comment by jenstornell** [comment]
Yes, you probably need to copy paste them. Thanks for all the work you've done here so far!

**Comment by aoimedia** [comment]
No worries. Copy/Paste job it is!

Happy to help. :)

**Comment by aoimedia** [comment]
All (?) themes now copied over to themes repo and tidied. Duplicate issues closed on plugin repo. Will add new themes as/when they become available.

**Comment by jenstornell** [comment]
Wow! I see you have added some labels to them as well. Really good labels actually! You probably know more about the themes than I do.

I think it could also be nice to tag the themes with categories, like "Blog, "Docs"  etc. What do you think about that?

**Comment by aoimedia** [comment]
Thanks! I love a tidy list. ;)

Great idea on the categories!
I'll add 'Blog' 'Docs' etc label/tags a little later today.

**Comment by jenstornell** [comment]
Great!

I don't know if you noticed but I also released a third repo:
https://github.com/jenstornell/kirby-solutions

It's for templates, snippets, blueprints, models, controllers, tutorials ect. For the extra things that don't fit in with plugins or themes.

Hopefully everything is covered now.

**Comment by aoimedia** [comment]
Yes, I noticed the 3rd repo.
So, basically repos for (1) Plugins, (2) Themes and (3) …everything else.

Good idea as it should make it easier to find things.

I'll shall of course be adding additional items to all 3 repos as/when I discover them. If I have access permissions I'll also look to move items to/from appropriate repos when I have more time.

**Comment by jenstornell** [comment]
I saw that you have also moved some panel fields to solutions. That's a tricky one. Is a panel field a plugin? It is not inside the plugins folder, but at the same time it works like a plugin for the panel. The same with kirbytext tags, that works like a plugin for panel content.

So, what is a solution and what is a plugin?

Soon there will probably be easier to deside:
https://forum.getkirby.com/t/kirby-plugin-bundles-plugin-repositories-and-meta-data/3398

Soon everything can be a plugin if it's done correctly.

So in the future, when a panel field is just a panel field, it should be in solutions, when it's added in a plugin folder it should be a plugin.

Until then, I'm not so sure. People see panel fields and kirbytext tags as plugin even if they are not in a plugin folder.

**Comment by aoimedia** [comment]
This is indeed a tricky one.

I actually noticed this last night. Some 'extras' did _not_ have a plugin label/tag yet definitely exhibited plugin behaviour and/or mentioned plugin within the repo's readme file. This is the main reason I stopped. Looks like a more complex area than first anticipated?

Also read the forum thread with interest.

I've used other CMS and most of the more popular platforms do indeed have standardised naming conventions when it comes to extras such plugin / extensions / overrides / controllers / modules / themes etc (as well as versioning). As the plugin and 3rd party 'add-on' library is growing for Kirby (which is great!) an accurate/standard means of categorisation would be helpful.

In the meantime, would you like me to move these items back to the plugin repo?

**Comment by jenstornell** [comment]
For the moment I feel like the panel fields works best in this plugins repository (people call them plugins still). But I think the ones with a tool label and the Isotope thing can still be in solutions.

I also have an idea for "inline" solutions where a solution does not exist in a repo or in a site, only as a snippet of code in an issue. That would make it really fast to share solutions. The difference to the solutions in the forum would be that a solution here could be updated or removed (closed) if outdated. They could also have labels. It would be nice to label them something special, like "Inline" or "Code".

**Comment by jenstornell** [comment]
I added an inline solution just to show what I mean:

https://github.com/jenstornell/kirby-solutions/issues/9

**Comment by aoimedia** [comment]
I'm thinking more about Kirby user/search convenience.
Are there really enough solutions (very few items are actually tagged 'tool') to warrant an additional repo? It might be easier just grouping them with plugins for the moment - saves the user having to leave one repository for another for very little gain.

Regarding 'inline' Kirby code 'snippets', would https://gist.github.com be simpler? I'm unsure if Gists are actually taggable in terms of labels but you do have the advantage of being able to edit, comment, commit and push to ensure code remains stable and up to date to reflect current and later versions of Kirby.

Just a thought.

**Comment by jenstornell** [comment]
Good point. Everything that is not a theme, is a plugin then.

I looked into the Gist thing and there seems to be no organisation. What I do like about it is that you can add more than one file and it saves revisions.

Maybe combine them. Use issues to label linked Gists. I don't really have a clear vision of it yet. Don't want to complicate things.

**Comment by samnabi** [comment]
> Good point. Everything that is not a theme, is a plugin then.

I agree with this. Two repos makes sense to me, and it seems we may be standardizing plugins soon with the bundles.

**Comment by aoimedia** [comment]
> “Everything that is not a theme is a plugin”

 … I like that. Simplicity wins. ;)

Fair points about Gist.
I really like the Gists/Issues combo idea. Best of both worlds, though a little more work to maintain.

I'll move those items out of solutions and back to the plugins repo later - then you can put the solutions repo on ice …for now.

**Comment by aoimedia** [comment]
All 'solutions' repo items now copied to 'plugins' repo. Aside from your code example 'solutions' repo is now empty.

**Comment by jenstornell** [comment]
I removed it. I'll open it again if I get a clear vision of how it's going to work, if not someone else does it before me.

**Comment by aoimedia** [comment]
👍🏻
