### ISSUE TITLE
Kirby-RelatedPages

### ISSUE THREAD

**Issue by aoimedia** [jenstornell/kirby-plugins#152]
https://github.com/texnixe/Kirby-RelatedPages

The RelatedPages plugin provides an easy, but flexible way of incorporating links (or other data) of related pages to the current page.

**Comment by texnixe** [comment]
This is an old version of the plugin that does not work with Kirby 2, and the plugin author is @Adspectus. I think there was an issue on the forum and the issue has been corrected, but not sure.

**Comment by jenstornell** [comment]
There are install instuctions for Kirby 2 as well?

**Comment by texnixe** [comment]
The installation is still the same, see https://github.com/getkirby/plugins/tree/master/relatedpages; I have contacted the plugin author, but pls. remove this link here and use the official one in the [getkirby plugins](https://github.com/getkirby/plugins/tree/master/relatedpages). I'm pretty sure this here is a duplicate anyway.

**Comment by jenstornell** [comment]
@texnixe I agree. I set it to broken yesterday but changed it to duplicate. We can keep it closed. Thanks!
