### ISSUE TITLE
Kirby Comments (beta)

### ISSUE THREAD

**Issue by aoimedia** [jenstornell/kirby-plugins#163]
https://github.com/dweidner/kirby-comments

A comment system for the lovely Kirby CMS.

**Comment by dweidner** [comment]
I will no longer work on this plugin, as others have implemented good alternatives already. Especially [Kirby Comments](https://github.com/Addpixel/KirbyComments) by @Addpixel looks promising. I think it will be better to contribute to this plugin instead.
