### ISSUE TITLE
Zurb Foundation 6 framework for Kirby

### ISSUE THREAD

**Issue by aoimedia** [jenstornell/kirby-plugins#173]
https://github.com/Tinkerism/Kirby-for-Zurb-Foundation-6

Zurb Foundation 6 framework Starterkit for Kirby CMS.

**Comment by Tinkerism** [comment]
Thanks to both of you for adding this, but as soon as this is finished (some day...) a better place than in plugins may be in templates.

**Comment by jenstornell** [comment]
For me this looks like alot more than just a theme because you have included the whole Kirby and the Panel as well. When it's that big package (fork of the Kirby core) we have chosen to add it here with the label "Core".

The question here is if it is a theme or if it's a full system?

**Comment by aoimedia** [comment]
It's a full Kirby package but it also contains a 'theme'.

Many of the themes within the (theme) repo also come with a full Kirby core pre-installed (giving the user a sort of 'quick starter'). I suppose it also depends a little on how the the developer is marketing their product?

**Comment by Tinkerism** [comment]
I did not change anything in the core. What I did is to ADD things, i.e. The Zurb Foundation Framework (CSS - SCSS will be added later and JS) plus some extras where I combined Kirby code with Foundation specifications in a way that hey can be re-used in different contexts. - The product (in its best sense) is not going to be marketed, only - maybe - with a donation possibility, sometime in the future. Men tack för allt!

**Comment by jenstornell** [comment]
Maybe it's like this then:

- Acts like a theme + no modification in the core = **Theme repo?**
- Acts like a theme + modification in the core = **Plugin repo?**

What do you think @Tinkerism @aoimedia

**Comment by aoimedia** [comment]
> Maybe it's like this then:
> 
>     Acts like a theme + no modification in the core = Theme repo?
>     Acts like a theme + modification in the core = Plugin repo?

I agree with this. Keeps things simple/straightforward too.

**Comment by aoimedia** [comment]
Now transferred to theme repo and closed.

**Comment by jenstornell** [comment]
https://github.com/jenstornell/kirby-themes/issues/63

**Comment by Tinkerism** [comment]
A natural distinction, I would say. Thanks for moving the theme!
