### ISSUE TITLE
Kirby Watermark Plugin

### ISSUE THREAD

**Issue by aoimedia** [jenstornell/kirby-plugins#214]
**Direct download** http://hydrosight.de/tmp/watermark.zip

> Image watermark plugin for Kirby CMS

**Comment by scsskid** [comment]
@aoimedia I'm interested in the plugin, but the link is dead, could you provide a working link? thank you

**Comment by aoimedia** [comment]
@scsskid Sorry, looks like the plugin no longer exists. I'm closing this for now. Thanks for the heads-up.

**Comment by texnixe** [comment]
I found the zip file in an old backup, you can download it from [here](https://cloud.spicyfamily.de/index.php/s/cOJwSj4JIosQVbb) until 2016-12-24. No idea if it is still working.
