### ISSUE TITLE
kirby-backup

### ISSUE THREAD

**Issue by aoimedia** [jenstornell/kirby-plugins#228]
**GitHub** https://github.com/1n3JgKl9pQ6cUMrW/kirby-backup

> Backup all of Kirby's content.

![687474703a2f2f692e696d6775722e636f6d2f7239526f6448552e676966](https://cloud.githubusercontent.com/assets/2782385/14847824/a19b6016-0c62-11e6-994b-b31e6b4e3a1c.gif)

**Comment by jenstornell** [comment]
No longer available
