### ISSUE TITLE
Kirby - Jumplist

### ISSUE THREAD

**Issue by aoimedia** [jenstornell/kirby-plugins#233]
**GitHub** https://github.com/1n3JgKl9pQ6cUMrW/Kirby-Jumplist

> Jumplist adds a menu in the upper-right corner of Kirby's panel, allowing you to quickly jump from page to page.

![kirby-jumplist](https://cloud.githubusercontent.com/assets/2782385/14847669/c0a95c3e-0c61-11e6-8615-0c2081c3e7ad.gif)

**Comment by jenstornell** [comment]
No longer available
