### ISSUE TITLE
Kirby - At a Glance

### ISSUE THREAD

**Issue by aoimedia** [jenstornell/kirby-plugins#234]
**GitHub** https://github.com/1n3JgKl9pQ6cUMrW/Kirby-At-a-Glance

> Shows a brief description of the main items in your site at the panel dashboard.

![kirby-at-a-glance](https://cloud.githubusercontent.com/assets/2782385/14847688/e4a04bfc-0c61-11e6-914b-9440bf1b8722.png)

**Comment by jenstornell** [comment]
No longer available
