### ISSUE TITLE
Kirby Auto Git Plugin

### ISSUE THREAD

**Issue by aoimedia** [jenstornell/kirby-plugins#235]
**Github** https://github.com/pedroborges/kirby-autogit

> Automatically push changes in your Kirby CMS installation to a remote repo.

**Comment by pedroborges** [comment]
Opsss, you found my "secret" project. This is being heavily developed. There are still lot's of great features on my list to add to it. Thanks for sharing!

**Comment by aoimedia** [comment]
Hi Pedro,

No problem. Looking forward to seeing how your project progresses. :)

**Comment by bugsysop** [comment]
Link on GitHub is dead

**Comment by aoimedia** [comment]
Thanks for the update. Looks like the project is now private or deleted. Now closed
