### ISSUE TITLE
kirby-plugin-gallery

### ISSUE THREAD

**Issue by aoimedia** [jenstornell/kirby-plugins#240]
**GitHub** https://github.com/julien-gargot/kirby-plugin-gallery

> Wrap pictures in a container to build a grid gallery with CSS.

**Comment by julien-gargot** [comment]
Wow, you're super fast.

Thank you add the plugin here, but he's not really ready to be shared.
I still have to work the code and write documentation so that it becomes useful for everyone and I will not do this now ;)

**Comment by jenstornell** [comment]
@julien-gargot 

Did you know that @aoimedia is from the future? You can almost tell by his profile photo. Soon he will publish plugins that no one has even thought of yet! ;)

**Comment by aoimedia** [comment]
Ha! …perhaps I am too fast? ;)

Shall we close this for the moment and re-open when plugin is completed?

**Comment by julien-gargot** [comment]
Probably better if you don't want to disappoint people with a useless code… ^^

**Comment by aoimedia** [comment]
No problem, Julien. :)

**Comment by jenstornell** [comment]
@julien-gargot Maybe you can reopen it when you feel ready for it? You already have access to do so.

**Comment by julien-gargot** [comment]
Sure, I let you know!
