### ISSUE TITLE
ChirpKard

### ISSUE THREAD

**Issue by aoimedia** [jenstornell/kirby-plugins#260]
**GitHub** https://github.com/cedwardsmedia/chirpkard

> ChirpKard is a snippet that generates Twitter Cards for your Kirby 2 site.

**Comment by demlak** [comment]
404

**Comment by jenstornell** [comment]
Broken url

**Comment by splorp** [comment]
I did find a fork of this plugin here:

https://github.com/AlexandrPoddubsky/chirpkard
