### ISSUE TITLE
Responsive Image Plugin

### ISSUE THREAD

**Issue by aoimedia** [jenstornell/kirby-plugins#278]
**GitHub** https://github.com/dweidner/kirby-responsive-image

> Easily create responsive images for a predefined set of layout breakpoints.

**Comment by dweidner** [comment]
Did not know about this repository. Thank you for listing the first version of my responsive image plugin.

**Comment by aoimedia** [comment]
You are very welcome, Daniel.
And thank _you_ for the Excellent Kirby plugin! 👍

**Comment by dweidner** [comment]
Will discontinue this plugin for now, [ImageKit](https://github.com/fabianmichael/kirby-imagekit) looks promising and will have a responsive image plugin in future releases.
