### ISSUE TITLE
Email obfuscate

### ISSUE THREAD

**Issue by aoimedia** [jenstornell/kirby-plugins#281]
**GitHub** https://github.com/jenstornell/email-obfuscate

> Obfuscate email addresses to prevent spam. It will probably not stop all, but hopefully stop some of them.

**Comment by jenstornell** [comment]
Will probably be close because of this:

https://forum.getkirby.com/t/email-obfuscate/4475

But we can have it open a while. I can close it later. :)

**Comment by aoimedia** [comment]
Oops! ;)

**Comment by jenstornell** [comment]
Deleted because of this: https://forum.getkirby.com/t/email-obfuscate/4475

Function is already in the core.
