### ISSUE TITLE
Kirby Theme loader

### ISSUE THREAD

**Issue by aoimedia** [jenstornell/kirby-plugins#289]
**GitHub** https://github.com/jenstornell/theme-loader

> Load and switch themes from `/site/themes/`

**Comment by aoimedia** [comment]
Original repo closed by developer.

**Comment by jenstornell** [comment]
Oops, should have closed the repo. I'm really terrible at maintaining this repo. I'm lucky to have you in here. :)

**Comment by aoimedia** [comment]
Ha! No problem. :)
