### ISSUE TITLE
Kirby-RelatedPages

### ISSUE THREAD

**Issue by jenstornell** [jenstornell/kirby-plugins#29]
https://github.com/getkirby/plugins/tree/master/relatedpages

> The RelatedPages plugin provides an easy, but flexible way of incorporating links (or other data) of related pages to the current page. The relationsship is considered by keywords in an arbitrary field of the content files.

**Comment by Thiousi** [comment]
This plugin is nowhere to be found. It's not in the new getkirby-plugins account https://github.com/getkirby-plugins
