### ISSUE TITLE
Kirby - Download Monitor

### ISSUE THREAD

**Issue by aoimedia** [jenstornell/kirby-plugins#291]
**GitHub** https://github.com/1n3JgKl9pQ6cUMrW/kirby-download-monitor

> Kirby Download Monitor allows you to get more insights in your downloads.

![kirby-download-monitor](https://cloud.githubusercontent.com/assets/2782385/16543029/1a6361c6-40b9-11e6-8566-e30c1e952465.gif)

**Comment by jenstornell** [comment]
No longer available
