### ISSUE TITLE
Kirby snippets for Atom

### ISSUE THREAD

**Issue by aoimedia** [jenstornell/kirby-plugins#298]
**GitHub** https://github.com/medienbaecker/kirby-atom

> Kirby snippets for Atom code/text editor

**Comment by medienbaecker** [comment]
This is by no means ready. I uploaded it for judbd in this [forum thread](https://forum.getkirby.com/t/atom-kirby-snippets/4596/4).

**Comment by aoimedia** [comment]
No problem, Thomas.
Sometimes I am too hasty. ;)
