### ISSUE TITLE
YAKME (Yet Another Kirby Markdown Editor)

### ISSUE THREAD

**Issue by aoimedia** [jenstornell/kirby-plugins#306]
**GitHub** https://github.com/1n3JgKl9pQ6cUMrW/Kirby-YAKME

> Kirby - YAKME (Yet Another Kirby Markdown Editor) is a markdown editor for Kirby.
> It uses the excellent Simple MDE (editor) from [https://simplemde.com](https://simplemde.com) as it's core-engine.

![kirby_yakme-logotype](https://cloud.githubusercontent.com/assets/2782385/18763773/c347e414-8106-11e6-9654-9c0bbd249e6f.png)

![kirby_yakme-capture](https://cloud.githubusercontent.com/assets/2782385/18763787/cd02b358-8106-11e6-9281-5bd6c70d78e5.gif)

![kirby_yakme-imagecheck](https://cloud.githubusercontent.com/assets/2782385/18763815/df4af9d0-8106-11e6-8f8c-ed0aebd8a522.gif)

![kirby_yakme-drag-and-drop](https://cloud.githubusercontent.com/assets/2782385/18763827/e9765fbc-8106-11e6-9e08-1e35ec8e3e4b.gif)

![kirby_yakme-styling](https://cloud.githubusercontent.com/assets/2782385/18763864/04d68156-8107-11e6-8106-acb496d1db1a.gif)

![kirby_yakme-video](https://cloud.githubusercontent.com/assets/2782385/18763875/10b024fa-8107-11e6-9814-c1a89cfe51f9.gif)

**Comment by jenstornell** [comment]
Does not work anymore
