### ISSUE TITLE
Kirby - Table

### ISSUE THREAD

**Issue by aoimedia** [jenstornell/kirby-plugins#309]
**GitHub** https://github.com/1n3JgKl9pQ6cUMrW/Kirby-Table

> Kirby - Table is a snippetfield for creating tables (cells) in Kirby.
> 
> It uses the excellent Kirby Snippetfield from [https://github.com/jenstornell/kirby-snippetfield](https://github.com/jenstornell/kirby-snippetfield) as it's core-engine - and can't do without.

![kirby_table-capture](https://cloud.githubusercontent.com/assets/2782385/16890146/e21638cc-4ae3-11e6-8508-85215a362ac2.gif)

**Comment by jenstornell** [comment]
No longer available
