### ISSUE TITLE
Kirby LISTER

### ISSUE THREAD

**Issue by aoimedia** [jenstornell/kirby-plugins#310]
**GitHub** https://github.com/1n3JgKl9pQ6cUMrW/kirby-lister

> Kirby - LISTER is a file-picker for the Kirby CMS, which supports a file preview (when available).
> It uses the excellent jQuery plug-in of [http://www.selectboxit.com](http://www.selectboxit.com)

![kirby-lister_screencapture](https://cloud.githubusercontent.com/assets/2782385/16897617/be948aa4-4bae-11e6-8c68-a72671ffee2c.gif)

**Comment by jenstornell** [comment]
Does not work anymore
