### ISSUE TITLE
Kirby Modules Field

### ISSUE THREAD

**Issue by aoimedia** [jenstornell/kirby-plugins#320]
**GitHub** https://github.com/lukaskleinschmidt/kirby-field-modules

> This field is build on top of [Kirby Modules Plugin](https://github.com/getkirby-plugins/modules-plugin). It provides a subpage like drag and drop for modules.

![preview](https://cloud.githubusercontent.com/assets/2782385/17702303/4df10406-63c5-11e6-98f8-eebf2dc816b6.gif)

**Comment by jenstornell** [comment]
Closing because of duplicateto https://github.com/jenstornell/kirby-plugins/issues/442

**Comment by aoimedia** [comment]
Ah, that explains it! ;)

Thanks, Jens.
