### ISSUE TITLE
Kirby - Plugins widget

### ISSUE THREAD

**Issue by aoimedia** [jenstornell/kirby-plugins#323]
**GitHub** https://github.com/1n3JgKl9pQ6cUMrW/kirby-plugins-widget

> Kirby - Plugins widget, is a simple widget for the Kirby CMS.
> It shows all plugins used in your site with the option to toggle their status (on / off).

![kirby-plugins-widget](https://cloud.githubusercontent.com/assets/2782385/17370009/69b9c764-5992-11e6-96fc-89225d682c10.gif)

**Comment by jenstornell** [comment]
No longer available
