### ISSUE TITLE
Kirby User Manager Panel Extention

### ISSUE THREAD

**Issue by aoimedia** [jenstornell/kirby-plugins#371]
**GitHub** https://github.com/LCD344/Kirby-userManager-panel-extention

> This plugin adds a user manager pages to the kirby panel. It uses datatables to allow you to search and filter your users, it also allows you to decide on a custom user folder (To seperate users from admins and editors), also if you use the custom folder you can have usernames that include @ and .
> 
> Also there are a bunch of extension planned the will make this panel extension even more useful.

**Comment by jenstornell** [comment]
You already added it 4 days ago?

https://github.com/jenstornell/kirby-plugins/issues/367

**Comment by aoimedia** [comment]
Oops. Well spotted.
I searched the repo before I posted too… no results (perhaps a typo on my part). Closed.

Monday… think I need more sleep! ;)
