### ISSUE TITLE
Kirby Keyword Density

### ISSUE THREAD

**Issue by aoimedia** [jenstornell/kirby-plugins#386]
**GitHub** https://github.com/jenstornell/kirby-keyword-density

> To make your page rank in the search engines, make sure that you have the important words in your text. This plugin will help you with that. Read more about keyword density on [Wikipedia](https://en.wikipedia.org/wiki/Keyword_density).

![screenshot](https://cloud.githubusercontent.com/assets/2782385/19774964/ba7140ee-9c66-11e6-84d7-eb0f5fdbb3e0.png)

![screenshot](https://cloud.githubusercontent.com/assets/2782385/19774981/c646b48a-9c66-11e6-9255-80866ca01e09.gif)

**Comment by jenstornell** [comment]
Closed this because it did not work as well as it should. It's replaced by
https://github.com/jenstornell/kirby-keyword-map
