### ISSUE TITLE
Kirby Comments

### ISSUE THREAD

**Issue by jenstornell** [jenstornell/kirby-plugins#391]
**Github:** https://github.com/Addpixel/KirbyComments/
**Demo:** https://kirby-comments.addpixel.net/demos/comments

>File based comments stored as subpages. Easy to setup. Easy to use. Flexible as hell.

![image](https://cloud.githubusercontent.com/assets/927011/19999109/c805b608-a270-11e6-89eb-f60495fd4d64.png)

**Comment by aoimedia** [comment]
Duplicate? Looks like the repo has been renamed only: https://github.com/jenstornell/kirby-plugins/issues/210

**Comment by jenstornell** [comment]
Ahhg, I thought I was faster than you this time. ;)
