### ISSUE TITLE
Kirby Menu Editor

### ISSUE THREAD

**Issue by aoimedia** [jenstornell/kirby-plugins#412]
**GitHub** https://github.com/jenstornell/kirby-menu-editor

> A menu editor for simple menus in Kirby CMS .

![screenshot-table](https://cloud.githubusercontent.com/assets/2782385/20968679/7e8cfd70-bc7d-11e6-9659-8e6290459c06.png)

![screenshot](https://cloud.githubusercontent.com/assets/2782385/20968684/884168e2-bc7d-11e6-847b-bbf2bf0697ba.png)

**Comment by jenstornell** [comment]
Closed
