### ISSUE TITLE
Kirby input field replacement

### ISSUE THREAD

**Issue by jenstornell** [jenstornell/kirby-plugins#81]
https://github.com/iksi/KirbyInputField

![](https://raw.githubusercontent.com/iksi/KirbyInputField/master/screenshot.png)

> The replacement input field adds a character counter that indicates whether a field is inside of a min/max range provided in the blueprint.

**It's build into the core**

**Comment by Thiousi** [comment]
This has been deprecated as it's part of the core. Maybe not worth keeping open?
